jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm playwright-core install chromium
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm test
    strategy:
      matrix:
        include:
          - node: 20
            os: ubuntu-latest
name: build
on:
  pull_request: {}
  push:
    branches:
      - master
