jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.repo.full_name == github.repository &&
            github.event.pull_request.head.ref || '' }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Actions"
      - run: pnpm install --frozen-lockfile
      - run: pnpm dev:prepare
      - run: pnpm lint
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/master'
        name: Release
        run: pnpm semantic-release
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm playwright-core install chromium
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm test
    strategy:
      matrix:
        include:
          - node: 20
            os: ubuntu-latest
name: build
on:
  pull_request: {}
  push:
    branches:
      - master
